id: I7BEBE398
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T23:42:30+00:00'
last_modified: '2022-06-08T10:55:35.553688+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1995
  title: མན་ངག་ཡོན་ཏན་རྒྱུད་ཀྱི་ལྷན་ཐབས་ཟུག་རྔུའི་ཚ་གདུངས་སེལ་བའི་ཀཏྤཱུ་ར་དུས་མིན་འཆི་ཞགས་གཅོད་པའི་རལ་གྲི
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3B99:
      image_group_id: I1CZ2035
      title: ''
      total_pages: 474
      order: 1
      base_file: 3B99.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
