id: P009422
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1995
  title: མན་ངག་ཡོན་ཏན་རྒྱུད་ཀྱི་ལྷན་ཐབས་ཟུག་རྔུའི་ཚ་གདུངས་སེལ་བའི་ཀཏྤཱུ་ར་དུས་མིན་འཆི་ཞགས་གཅོད་པའི་རལ་གྲི
  author: ''
  volumes: {}
